name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main 

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Build and Deploy
        run: |
          mkdir -p public
          echo "<!DOCTYPE html><html><head><title>My Page</title></head><body><h1>Hello, GitHub Pages!</h1></body></html>" > public/index.html
        
      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v1

  deployment:
    runs-on: ubuntu-latest
    needs: deploy

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1